In [1]:
import pandas as pd

In [2]:
train_df=pd.read_csv(r"C:\Users\Nidhi\Desktop\8b9aafccf7da11ee\dataset\train.csv")

In [3]:
train_df.head()

candidate_id gender  age  height_in_cm  weight_in_lbs  left_eyesight_lvl  \
0        CAN_1   Male   35           170         165.35                1.0   
1        CAN_2   Male   30           180         176.37                0.9   
2        CAN_3   Male   40           165         165.35                1.2   
3        CAN_4   Male   50           175         176.37                1.5   
4        CAN_5   Male   50           165         132.28                1.0   

   right_eyesight_lvl   can_hear_left_ear  can_hear_right_ear  \
0                 1.0  Slightly Defective  Slightly Defective   
1                 1.2  Slightly Defective  Slightly Defective   
2                 1.5  Slightly Defective  Slightly Defective   
3                 1.2  Slightly Defective  Slightly Defective   
4                 1.2  Slightly Defective  Slightly Defective   

   blood_pressure_lvl1  ...  bad_cholestrol_lvl  hemoglobin_lvl  urea_lvl  \
0                120.0  ...               126.0            17.1       1.0   
1                130.0  ...               148.0            15.8       1.0   
2                120.0  ...                74.0            15.8       1.0   
3                145.0  ...               104.0            17.6       1.0   
4                138.0  ...               117.0            13.8       1.0   

   creatinine_lvl  liver_enzyme_lvl1  liver_enzyme_lvl2   smoking_habit  \
0             1.0               21.0               35.0  Does not Smoke   
1             0.9               20.0               36.0    Chain Smoker   
2             0.9               47.0               32.0  Does not Smoke   
3             1.1               29.0               34.0  Does not Smoke   
4             0.8               19.0               12.0  Does not Smoke   

   drinking_habit  residential_area  triglyceride_lvl  
0               Y              Town              92.0  
1               N             Urban             121.0  
2               N             Rural             104.0  
3               N              Town             106.0  
4               N             Urban             104.0  

[5 rows x 24 columns]

In [4]:
train_df.drop(['candidate_id'],axis=1,inplace=True)

In [5]:
train_x = train_df.drop("triglyceride_lvl", axis=1) # drop labels for training set
train_y = train_df["triglyceride_lvl"].copy()

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")), #numerical
        ('std_scaler', StandardScaler())   # feature scaling
    ])

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

df_numerical=train_x.drop(["gender",'can_hear_left_ear','can_hear_right_ear','smoking_habit','drinking_habit','residential_area'], axis=1)
num_attributes=list(df_numerical) # pipeline dont take data frames
cat_attributes=["gender",'can_hear_left_ear','can_hear_right_ear','smoking_habit','drinking_habit','residential_area']


full_pipeline=ColumnTransformer([ ("num", num_pipeline, num_attributes),
        ("cat", OneHotEncoder(), cat_attributes)])

In [8]:
df_prepared = full_pipeline.fit_transform(train_x)

In [9]:
pd.DataFrame(df_prepared)

0         1         2         3         4         5         6   \
0     -0.888464  0.752873  0.933058  0.029189  0.036950 -0.175667  0.391035   
1     -1.241404  1.782694  1.333056 -0.133864  0.375883  0.510138  0.592626   
2     -0.535524  0.237962  0.933058  0.355296  0.884283 -0.175667 -0.616916   
3      0.170357  1.267784  1.333056  0.844455  0.375883  1.538846  1.096601   
4      0.170357  0.237962 -0.267297  0.029189  0.375883  1.058782  0.592626   
...         ...       ...       ...       ...       ...       ...       ...   
22395  0.170357  1.267784 -1.067655 -0.296917  0.036950 -1.547278 -1.120891   
22396 -1.241404  0.237962  0.933058 -0.786076  0.036950  0.853041  0.895011   
22397  1.229177 -1.306770 -0.267297 -0.296917 -0.301983  2.087491  0.491831   
22398  0.170357  0.752873 -0.667658  0.029189  0.036950 -0.655731 -0.213735   
22399 -0.182583  0.752873  0.933058  0.355296  0.884283  1.881749  1.398987   

             7         8         9   ...   22   23   24   25   26   27   28  \
0     -0.064860 -0.061461 -0.164628  ...  0.0  1.0  0.0  0.0  0.0  1.0  0.0   
1      0.222802  0.835012 -0.039589  ...  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
2     -0.105954 -1.521431 -0.289668  ...  0.0  1.0  0.0  0.0  1.0  0.0  0.0   
3     -0.229238  0.143447  0.335531  ...  0.0  1.0  0.0  0.0  1.0  0.0  0.0   
4      0.017329  0.092220  0.067589  ...  0.0  1.0  0.0  0.0  1.0  0.0  0.0   
...         ...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...   
22395 -0.393616  1.270441  0.246217  ...  0.0  1.0  0.0  0.0  0.0  1.0  0.0   
22396  0.921410  1.654644 -0.307531  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0   
22397  2.113152  3.012159  0.174766  ...  0.0  1.0  0.0  0.0  1.0  0.0  0.0   
22398 -0.311427  1.757098 -0.021726  ...  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
22399  0.469370  0.604490  0.514160  ...  0.0  1.0  0.0  0.0  0.0  1.0  0.0   

        29   30   31  
0      0.0  1.0  0.0  
1      0.0  0.0  1.0  
2      1.0  0.0  0.0  
3      0.0  1.0  0.0  
4      0.0  0.0  1.0  
...    ...  ...  ...  
22395  0.0  1.0  0.0  
22396  0.0  1.0  0.0  
22397  0.0  1.0  0.0  
22398  0.0  1.0  0.0  
22399  0.0  1.0  0.0  

[22400 rows x 32 columns]

In [19]:
#applying lasso reg
from sklearn.linear_model import Lasso
lasso_reg=Lasso(alpha=2)


In [20]:
lasso_reg.fit(df_prepared,train_y)

Lasso(alpha=2)

In [21]:
lp = lasso_reg.predict(df_prepared)

In [24]:
lasso_reg.coef_

array([-6.21493011e-01, -3.57516759e+01,  2.74311901e+01,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.90253867e+00,  6.56253939e+00,
        3.25945536e+01,  2.69397019e+00, -2.48200014e+01,  6.56446531e+00,
        0.00000000e+00,  6.55206663e-01,  0.00000000e+00,  3.91439646e+00,
       -2.88431108e+01,  6.52596755e-15, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  6.95549142e+00, -4.78620655e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00])

In [22]:
import numpy as np
from sklearn.metrics import mean_squared_error
lp_mse = mean_squared_error(train_y, lp)
lp_rmse = np.sqrt(lp_mse)
lp_rmse

64.46843031759718

In [25]:
from sklearn.linear_model import SGDRegressor

In [34]:
sgd_reg=SGDRegressor(penalty='l2')

In [35]:
sgd_reg.fit(df_prepared,train_y)

SGDRegressor()

In [36]:
sp = sgd_reg.predict(df_prepared)

In [37]:
sp_mse = mean_squared_error(train_y, sp)
sp_rmse = np.sqrt(sp_mse)
sp_rmse

82904861.69761829

In [47]:
# apply ridge
from sklearn.linear_model import Ridge
r_reg=Ridge(alpha=0.1, solver='cholesky')
r_reg.fit(df_prepared,train_y)

Ridge(alpha=0.1, solver='cholesky')

In [48]:
rp = r_reg.predict(df_prepared)

In [49]:
rp_mse = mean_squared_error(train_y, rp)
rp_rmse = np.sqrt(rp_mse)
rp_rmse

62.86341075922536

In [62]:
#apply elastic net
from sklearn.linear_model import ElasticNet
en_reg=ElasticNet(alpha=0.5, l1_ratio=0.8)
en_reg.fit(df_prepared,train_y)

ElasticNet(alpha=0.5, l1_ratio=0.8)

In [63]:
en = en_reg.predict(df_prepared)

In [64]:
en_mse = mean_squared_error(train_y, en)
en_rmse = np.sqrt(en_mse)
en_rmse

64.85274435445062

In [66]:
from sklearn.metrics import r2_score
r2_score(train_y, en)

0.4089952015707785

In [67]:
#apply random forest
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(n_estimators=3, random_state=42)
forest_reg.fit(df_prepared,train_y)

RandomForestRegressor(n_estimators=3, random_state=42)

In [68]:
import numpy as np
from sklearn.metrics import mean_squared_error
housing_predictions = forest_reg.predict(df_prepared)
forest_mse = mean_squared_error(train_y, housing_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

19.364998698765117

In [69]:
from sklearn.metrics import r2_score
r2_score(train_y, housing_predictions)

0.9473050212374391

In [12]:
from sklearn.model_selection import GridSearchCV
param_grid=[{'n_estimators':[3,10,30],'max_features':[2,4,6,8]}, {'bootstrap':[False],'n_estimators':[3,10],'max_features':[2,4,6,8]}]
grid_search = GridSearchCV(forest_reg, param_grid, cv=3,
                           scoring='neg_mean_squared_error',
                           return_train_score=True)
grid_search.fit(df_prepared, train_y)

GridSearchCV(cv=3,
             estimator=RandomForestRegressor(n_estimators=3, random_state=42),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10]}],
             return_train_score=True, scoring='neg_mean_squared_error')

In [13]:
grid_search.best_params_

{'max_features': 8, 'n_estimators': 30}

In [14]:
grid_search.best_estimator_.feature_importances_

array([0.03108365, 0.09719291, 0.05404539, 0.01876125, 0.01818219,
       0.03145661, 0.03076731, 0.04548317, 0.13831035, 0.16867322,
       0.12657536, 0.05402471, 0.00438179, 0.01720832, 0.0323527 ,
       0.05529526, 0.01440998, 0.00777689, 0.00123264, 0.00130144,
       0.00117231, 0.00103013, 0.00759131, 0.00914763, 0.00315989,
       0.00200067, 0.00524058, 0.00675235, 0.00230797, 0.00448757,
       0.0043723 , 0.00422212])

In [15]:
len(grid_search.best_estimator_.feature_importances_)

32

In [16]:
feature_importances=grid_search.best_estimator_.feature_importances_

In [17]:
from sklearn.base import BaseEstimator, TransformerMixin

def indices_of_top_k(arr, k):
    return np.sort(np.argpartition(np.array(arr), -k)[-k:])

class TopFeatureSelector(BaseEstimator, TransformerMixin):
    def __init__(self, feature_importances, k):
        self.feature_importances = feature_importances
        self.k = k
    def fit(self, X, y=None):
        self.feature_indices_ = indices_of_top_k(self.feature_importances, self.k)
        return self
    def transform(self, X):
        return X[:, self.feature_indices_]

In [18]:
k=5
top_k_feature_indices = indices_of_top_k(feature_importances, k)
top_k_feature_indices

array([ 1,  8,  9, 10, 15], dtype=int64)

In [19]:
attributes=num_attribs = list(df_numerical)
cat_attributes=["gender",'can_hear_left_ear','can_hear_right_ear','smoking_habit','drinking_habit','residential_area']


In [20]:
attributes = num_attributes +  cat_attributes

In [21]:
sorted(zip(feature_importances, attributes), reverse=True)

[(0.16867321897272353, 'good_cholestrol_lvl'),
 (0.1383103471580989, 'total_cholestrol'),
 (0.12657535557770766, 'bad_cholestrol_lvl'),
 (0.09719290940707796, 'height_in_cm'),
 (0.05529526430535548, 'liver_enzyme_lvl2'),
 (0.054045390364645944, 'weight_in_lbs'),
 (0.05402471208917443, 'hemoglobin_lvl'),
 (0.04548317485287686, 'glucose_lvl'),
 (0.032352700969994604, 'liver_enzyme_lvl1'),
 (0.03145661435186924, 'blood_pressure_lvl1'),
 (0.031083648303030224, 'age'),
 (0.03076730840560785, 'blood_pressure_lvl2'),
 (0.018761251594557927, 'left_eyesight_lvl'),
 (0.018182190538034514, 'right_eyesight_lvl'),
 (0.01720832435121879, 'creatinine_lvl'),
 (0.014409976788046926, 'gender'),
 (0.0077768930164526595, 'can_hear_left_ear'),
 (0.004381790083788293, 'urea_lvl'),
 (0.0013014368475729207, 'smoking_habit'),
 (0.001232637054509061, 'can_hear_right_ear'),
 (0.001172305672804559, 'drinking_habit'),
 (0.0010301341567470418, 'residential_area')]

In [22]:
sorted(zip(feature_importances, attributes), reverse=True)[:k]

[(0.16867321897272353, 'good_cholestrol_lvl'),
 (0.1383103471580989, 'total_cholestrol'),
 (0.12657535557770766, 'bad_cholestrol_lvl'),
 (0.09719290940707796, 'height_in_cm'),
 (0.05529526430535548, 'liver_enzyme_lvl2')]

In [23]:
preparation_and_feature_selection_pipeline = Pipeline([
    ('preparation', full_pipeline),
    ('feature_selection', TopFeatureSelector(feature_importances, k))
])

In [24]:
housing_prepared_top_k_features = preparation_and_feature_selection_pipeline.fit_transform(train_x)

In [25]:
housing_prepared_top_k_features

array([[ 0.75287297, -0.06146097, -0.16462845,  0.26958493,  0.49137002],
       [ 1.78269433,  0.83501165, -0.03958853,  0.7280491 ,  0.54174757],
       [ 0.23796229, -1.52143067, -0.28966836, -0.81405764,  0.34023737],
       ...,
       [-1.30676974,  3.01215944,  0.17476561,  1.39490607, -0.56655851],
       [ 0.75287297,  1.75709777, -0.02172569,  1.58245959, -0.66731361],
       [ 0.75287297,  0.60449012,  0.51415967, -0.16803996,  0.03797208]])

In [26]:
housing_prepared_top_k_features[0:3]

array([[ 0.75287297, -0.06146097, -0.16462845,  0.26958493,  0.49137002],
       [ 1.78269433,  0.83501165, -0.03958853,  0.7280491 ,  0.54174757],
       [ 0.23796229, -1.52143067, -0.28966836, -0.81405764,  0.34023737]])

In [27]:
df_prepared[0:3, top_k_feature_indices]

array([[ 0.75287297, -0.06146097, -0.16462845,  0.26958493,  0.49137002],
       [ 1.78269433,  0.83501165, -0.03958853,  0.7280491 ,  0.54174757],
       [ 0.23796229, -1.52143067, -0.28966836, -0.81405764,  0.34023737]])

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import expon, reciprocal
from sklearn.svm import SVR

# see https://docs.scipy.org/doc/scipy/reference/stats.html
# for `expon()` and `reciprocal()` documentation and more probability distribution functions.

# Note: gamma is ignored when kernel is "linear"
param_distribs = {
        'kernel': ['linear', 'rbf'],
  'C': np.linspace(20, 200000, num=10),  # Example range for 'C' parameter
    'gamma': np.linspace(0.001, 1.0, num=10)
    }

svm_reg = SVR()
rnd_search = RandomizedSearchCV(svm_reg, param_distributions=param_distribs,
                                n_iter=3, cv=3, scoring='neg_mean_squared_error',
                                verbose=2, random_state=42)
rnd_search.fit(df_prepared, train_y)

Fitting 3 folds for each of 3 candidates, totalling 9 fits
[CV] END .................C=88900.0, gamma=0.778, kernel=rbf; total time= 2.2min
[CV] END .................C=88900.0, gamma=0.778, kernel=rbf; total time= 2.3min
[CV] END .................C=88900.0, gamma=0.778, kernel=rbf; total time= 2.3min
[CV] END ....................C=20.0, gamma=0.778, kernel=rbf; total time=  48.0s
[CV] END ....................C=20.0, gamma=0.778, kernel=rbf; total time=  49.0s
[CV] END ....................C=20.0, gamma=0.778, kernel=rbf; total time=  48.2s


In [ ]:
prepare_select_and_predict_pipeline = Pipeline([
    ('preparation', full_pipeline),
    ('feature_selection', TopFeatureSelector(feature_importances, k)),
    ('svm_reg', SVR(**rnd_search.best_params_))
])

In [ ]:
prepare_select_and_predict_pipeline.fit(train_x,train_y)

In [ ]:
some_data = housing_train_x.iloc[:4]
some_labels = housing_train_y.iloc[:4]

print("Predictions:\t", prepare_select_and_predict_pipeline.predict(some_data))
print("Labels:\t\t", list(some_labels))

In [ ]:
full_pipeline.named_transformers_["cat"].handle_unknown = 'ignore'

param_grid = [{
    'preparation__num__imputer__strategy': ['mean', 'median', 'most_frequent'],
    'feature_selection__k': list(range(1, len(feature_importances) + 1))
}]

grid_search_prep = GridSearchCV(prepare_select_and_predict_pipeline, param_grid, cv=2,
                                scoring='neg_mean_squared_error', verbose=2)
grid_search_prep.fit(housing_train_x, housing_train_y)

In [ ]:
grid_search_prep.best_params_